#!/usr/bin/env bash
set -Eeuo pipefail

readonly FAUST_TICK_START_DEFAULT="2026-09-27T13:00:00Z"
readonly FAUST_TICK_LENGTH_MS="45000"
readonly FAUST_FLAG_LIFETIME_TICKS="5"
readonly PCAP_BROKER_REV="fe3c0b2cdfa2fcf3272ecfcf5392b241082beaa1"
readonly CADDY_IMAGE="caddy:2.11.4-alpine"
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
readonly SCRIPT_DIR
readonly PCAP_SPOOL_DIR="/var/spool/rose-pcap"
readonly FORWARDER_STATE_DIR="/var/lib/rose-forwarder"

log() { printf '[+] %s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }
need_command() { command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"; }

usage() {
    cat <<'EOF'
Configure Tulip for FAUST CTF over the game VPN using live PCAP-over-IP.

Usage:
  setup-tulip-ecsc.sh offsite --team-id ID [options]
  setup-tulip-ecsc.sh vulnbox --public-key-file FILE [options]
  setup-tulip-ecsc.sh doctor [--tulip-dir DIR]

Offsite server:
  --team-id ID             FAUST team number; vulnbox defaults to fd66:666:<ID>::2
  --vulnbox-ip ADDR        Override the vulnbox IPv4/IPv6 address
  --tulip-dir DIR          Default: ./tulip beside this script
  --ui-vpn-ip ADDR         Bind Tulip directly to this address instead of public HTTPS
  --ui-port PORT           Direct UI port with --ui-vpn-ip; default: 3000
  --public-ip ADDR         Public UI IP when no domain is used
  --public-port PORT       Public HTTPS port; default: 443, useful fallback: 8443
  --domain NAME            Public DNS name; provides browser-trusted HTTPS
  --auth-user USER         Public HTTPS username; default: team
  --auth-password PASS     Public HTTPS password; generated when omitted
  --tick-start TIMESTAMP   Default: FAUST 2026 scoring start
  --service PORT:NAME      Initial mapping; repeat as needed
  --push-public-key-file FILE  Vulnbox forwarding key; enables durable push ingest
  --push-public-key KEY    Vulnbox forwarding key as a literal SSH public key
  --start                  Verify SSH, build, and start the stack
  --force                  Replace changed generated files

Vulnbox:
  --public-key-file FILE    Public capture key generated by offsite mode
  --public-key KEY          Public capture key as a literal ssh-ed25519/... string
  --team-id ID              FAUST team number; vulnbox IP becomes fd66:666:<ID>::2
  --vulnbox-ip ADDR         Override the vulnbox IPv4/IPv6 address in services.json
  --game-interface IFACE   Auto-detected when omitted
  --capture-filter FILTER  Default excludes SSH, retired stream 4242, and 4444
  --offsite-host HOST      Enable durable PCAP forwarding to this Rose server
  --offsite-port PORT      SSH port on the offsite host; default: 22
  --offsite-user USER      Restricted receiver account; default: root
  --offsite-dir DIR        Receiver traffic directory; default: /root/tulip/.ecsc/traffic
  --start                  Start capture, staging, forwarding, and health timers
  --force                  Replace changed generated files

Recommended durable order:
  1. Run offsite once without --start; copy .ecsc/ssh/id_ed25519.pub to the vulnbox.
  2. Run vulnbox with --public-key-file; it creates /root/.ssh/rose-pcap-push.pub.
  3. Copy that push public key to the offsite host.
  4. Run offsite with --push-public-key-file and --start.
  5. Run vulnbox with --offsite-host and --start.

The vulnbox rotates PCAPs into a durable queue. Failed transfers stay queued and
are retried every five seconds. The legacy offsite-pull stream remains available
only when no forwarding key has been configured.
EOF
}

write_generated() {
    local target="$1" force="$2" mode="${3:-0600}" tmp
    tmp="$(mktemp)"
    cat >"$tmp"
    if [[ -e "$target" ]]; then
        if cmp -s "$tmp" "$target"; then
            rm -f -- "$tmp"
            chmod "$mode" "$target"
            return
        fi
        if [[ "$force" != 1 ]]; then
            rm -f -- "$tmp"
            die "$target differs; inspect it or rerun with --force"
        fi
    fi
    mkdir -p -- "$(dirname -- "$target")"
    chmod "$mode" "$tmp"
    mv -f -- "$tmp" "$target"
}

validate_ipv4() {
    local ip="$1" octet
    local -a octets
    [[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1
    IFS=. read -r -a octets <<<"$ip"
    for octet in "${octets[@]}"; do
        ((10#$octet >= 0 && 10#$octet <= 255)) || return 1
    done
}

validate_ip() {
    local ip="$1"
    if validate_ipv4 "$ip"; then return 0; fi
    [[ "$ip" =~ ^[0-9A-Fa-f:.]+$ && "$ip" == *:* ]]
}

validate_port() {
    local port="$1"
    [[ "$port" =~ ^[0-9]+$ ]] || return 1
    ((port >= 1 && port <= 65535))
}

json_escape() {
    local value="$1"
    value=${value//\\/\\\\}; value=${value//\"/\\\"}
    value=${value//$'\n'/\\n}; value=${value//$'\r'/\\r}; value=${value//$'\t'/\\t}
    printf '%s' "$value"
}

url_host() {
    local host="$1"
    if [[ "$host" == *:* && "$host" != \[* ]]; then
        printf '[%s]' "$host"
    else
        printf '%s' "$host"
    fi
}

default_tulip_dir() {
    if [[ -f "$SCRIPT_DIR/docker-compose.yml" ]]; then
        printf '%s' "$SCRIPT_DIR"
    else
        printf '%s' "$SCRIPT_DIR/tulip"
    fi
}

build_services_json() {
    local vm_ip="$1"; shift
    local result='[' first=1 spec port name
    if (($# == 0)); then
        printf '[{"ip":"%s","port":-1,"name":"other"}]' "$(json_escape "$vm_ip")"
        return
    fi
    for spec in "$@"; do
        [[ "$spec" == *:* ]] || die "invalid --service '$spec'; expected PORT:NAME"
        port="${spec%%:*}"; name="${spec#*:}"
        validate_port "$port" || die "service port must be in 1-65535: $port"
        [[ -n "$name" ]] || die "service name cannot be empty"
        ((first)) || result+=','; first=0
        result+="{\"ip\":\"$(json_escape "$vm_ip")\",\"port\":$port,\"name\":\"$(json_escape "$name")\"}"
    done
    printf '%s]' "$result"
}

install_vulnbox_dependencies() {
    if command -v tcpdump >/dev/null 2>&1 && command -v python3 >/dev/null 2>&1 \
        && command -v ss >/dev/null 2>&1 && command -v sshd >/dev/null 2>&1 \
        && command -v rsync >/dev/null 2>&1 && command -v flock >/dev/null 2>&1; then
        return
    fi
    if command -v apt-get >/dev/null 2>&1; then
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y \
            tcpdump python3 iproute2 openssh-server openssh-client rsync util-linux findutils
    elif command -v dnf >/dev/null 2>&1; then
        dnf install -y tcpdump python3 iproute openssh-server openssh-clients rsync util-linux findutils
    elif command -v apk >/dev/null 2>&1; then
        apk add --no-cache tcpdump python3 iproute2 openssh-server openssh-client rsync util-linux findutils
    else
        die "install tcpdump, python3, iproute2, OpenSSH, rsync, and util-linux first"
    fi
}

install_offsite_dependencies() {
    local need_docker=0 need_compose=0
    command -v docker >/dev/null 2>&1 || need_docker=1
    if ((need_docker == 0)) && ! docker compose version >/dev/null 2>&1; then need_compose=1; fi

    if ((need_docker || need_compose)) || ! command -v rsync >/dev/null 2>&1 \
        || ! command -v ssh-keygen >/dev/null 2>&1 || ! command -v sshd >/dev/null 2>&1 \
        || ! command -v python3 >/dev/null 2>&1; then
        [[ ${EUID:-$(id -u)} -eq 0 ]] \
            || die "missing offsite dependencies; rerun as root so Docker Compose v2 and support tools can be installed"

        if command -v apt-get >/dev/null 2>&1; then
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y \
                ca-certificates curl openssl openssh-client openssh-server python3 rsync
            if ((need_docker)); then
                DEBIAN_FRONTEND=noninteractive apt-get install -y docker.io
            fi
            if ! docker compose version >/dev/null 2>&1; then
                DEBIAN_FRONTEND=noninteractive apt-get install -y docker-compose-v2 \
                    || DEBIAN_FRONTEND=noninteractive apt-get install -y docker-compose-plugin
            fi
        elif command -v dnf >/dev/null 2>&1; then
            dnf install -y ca-certificates curl openssl openssh-clients openssh-server python3 rsync
            if ((need_docker)); then
                dnf install -y dnf-plugins-core
                if [[ -r /etc/os-release ]]; then
                    # shellcheck source=/dev/null
                    source /etc/os-release
                fi
                local repo_family="${ID:-centos}"
                case "$repo_family" in fedora) ;; *) repo_family=centos ;; esac
                dnf config-manager --add-repo "https://download.docker.com/linux/$repo_family/docker-ce.repo"
                dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            elif ((need_compose)); then
                dnf install -y docker-compose-plugin
            fi
        elif command -v apk >/dev/null 2>&1; then
            apk add --no-cache ca-certificates curl openssl openssh-client openssh-server python3 rsync docker docker-cli-compose
        else
            die "unsupported package manager; install Docker Engine, Compose v2, OpenSSH, Python 3, and rsync"
        fi
    fi

    if command -v systemctl >/dev/null 2>&1; then
        systemctl enable --now docker
        systemctl enable --now ssh 2>/dev/null || systemctl enable --now sshd
    elif command -v rc-service >/dev/null 2>&1; then
        rc-update add docker default 2>/dev/null || true
        rc-service docker start
    fi
    need_command docker
    docker compose version >/dev/null 2>&1 || die "Docker Compose v2 installation failed"
}

ensure_timescale_clang19() {
    local tulip_dir="$1" dockerfile="$1/services/timescale/Dockerfile"
    [[ -f "$dockerfile" ]] || die "Timescale Dockerfile missing: $dockerfile"
    if grep -Eq 'clang15|llvm15' "$dockerfile"; then
        [[ -e "$dockerfile.before-clang19" ]] || cp -a -- "$dockerfile" "$dockerfile.before-clang19"
        python3 - "$dockerfile" <<'PYTHON'
from pathlib import Path
import sys

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
text = text.replace("clang15", "clang19").replace("llvm15", "llvm19")
path.write_text(text, encoding="utf-8")
PYTHON
        log "updated the Timescale build from clang/llvm 15 to 19 (backup: $dockerfile.before-clang19)"
    fi
    grep -Eq 'clang19.*llvm19|llvm19.*clang19' "$dockerfile" \
        || die "$dockerfile must install clang19 and llvm19"
}

offsite_main() {
    local team_id="" vulnbox_ip="" tulip_dir
    tulip_dir="$(default_tulip_dir)"
    local public_ip="" public_port=443 domain="" ui_vpn_ip="" ui_port=3000
    local auth_user="team" auth_password="" tick_start="$FAUST_TICK_START_DEFAULT"
    local push_public_key_file="" push_public_key_literal="" durable_push=0
    local start=0 force=0
    local -a service_specs=()

    while (($#)); do
        case "$1" in
            --team-id) team_id="${2:?missing value}"; shift 2 ;;
            --vulnbox-ip) vulnbox_ip="${2:?missing value}"; shift 2 ;;
            --tulip-dir) tulip_dir="${2:?missing value}"; shift 2 ;;
            --ui-vpn-ip) ui_vpn_ip="${2:?missing value}"; shift 2 ;;
            --ui-port) ui_port="${2:?missing value}"; shift 2 ;;
            --public-ip) public_ip="${2:?missing value}"; shift 2 ;;
            --public-port) public_port="${2:?missing value}"; shift 2 ;;
            --domain) domain="${2:?missing value}"; shift 2 ;;
            --auth-user) auth_user="${2:?missing value}"; shift 2 ;;
            --auth-password) auth_password="${2:?missing value}"; shift 2 ;;
            --tick-start) tick_start="${2:?missing value}"; shift 2 ;;
            --service) service_specs+=("${2:?missing value}"); shift 2 ;;
            --push-public-key-file) push_public_key_file="${2:?missing value}"; shift 2 ;;
            --push-public-key) push_public_key_literal="${2:?missing value}"; shift 2 ;;
            --start) start=1; shift ;;
            --force) force=1; shift ;;
            -h|--help) usage; exit 0 ;;
            *) die "unknown offsite option: $1" ;;
        esac
    done

    [[ "$team_id" =~ ^[0-9]+$ ]] || die "--team-id must be a number"
    ((team_id >= 1 && team_id <= 9999)) || die "--team-id must be between 1 and 9999"
    vulnbox_ip="${vulnbox_ip:-fd66:666:${team_id}::2}"
    validate_ip "$vulnbox_ip" || die "invalid vulnbox IP: $vulnbox_ip"
    validate_port "$public_port" || die "invalid --public-port"
    validate_port "$ui_port" || die "invalid --ui-port"
    if [[ -n "$public_ip" ]]; then validate_ip "$public_ip" || die "invalid public IP: $public_ip"; fi
    if [[ -n "$ui_vpn_ip" ]]; then validate_ip "$ui_vpn_ip" || die "invalid --ui-vpn-ip"; fi
    if [[ -n "$domain" ]]; then
        [[ "$domain" =~ ^[A-Za-z0-9]([A-Za-z0-9.-]*[A-Za-z0-9])?$ && "$domain" == *.* ]] \
            || die "invalid --domain"
    fi
    [[ -d "$tulip_dir" && -f "$tulip_dir/docker-compose.yml" ]] || die "Tulip checkout not found: $tulip_dir"

    install_offsite_dependencies
    need_command ssh-keygen; need_command ssh-keyscan; need_command python3; need_command rsync
    tulip_dir="$(cd -- "$tulip_dir" && pwd -P)"
    ensure_timescale_clang19 "$tulip_dir"
    mkdir -p -- "$tulip_dir/.ecsc/ssh" "$tulip_dir/.ecsc/metadata" "$tulip_dir/.ecsc/traffic"

    local private_key="$tulip_dir/.ecsc/ssh/id_ed25519"
    local public_key="$private_key.pub"
    local known_hosts="$tulip_dir/.ecsc/ssh/known_hosts"
    if [[ ! -s "$private_key" || ! -s "$public_key" ]]; then
        [[ ! -e "$private_key" && ! -e "$public_key" ]] \
            || die "incomplete SSH key pair under $tulip_dir/.ecsc/ssh"
        ssh-keygen -q -t ed25519 -N '' -C ecsc-tulip-capture -f "$private_key"
    fi
    chmod 0600 "$private_key"; chmod 0644 "$public_key"
    [[ -e "$known_hosts" ]] || : >"$known_hosts"
    chmod 0644 "$known_hosts"

    local stored_push_key="$tulip_dir/.ecsc/ssh/vulnbox-push.pub"
    if [[ -n "$push_public_key_literal" ]]; then
        printf '%s\n' "$push_public_key_literal" | write_generated "$stored_push_key" "$force" 0644
    elif [[ -n "$push_public_key_file" ]]; then
        [[ -s "$push_public_key_file" ]] || die "push public key file is empty or missing: $push_public_key_file"
        cat "$push_public_key_file" | write_generated "$stored_push_key" "$force" 0644
    fi

    if [[ -s "$stored_push_key" ]]; then
        [[ ${EUID:-$(id -u)} -eq 0 ]] || die "durable push receiver installation requires root"
        [[ "$tulip_dir" =~ ^/[A-Za-z0-9_./-]+$ ]] \
            || die "durable push requires a Tulip path without spaces or shell metacharacters"
        local push_key_type push_key_data receiver=/usr/local/sbin/rose-pcap-receive
        read -r push_key_type push_key_data _ <"$stored_push_key"
        case "$push_key_type" in ssh-ed25519|ecdsa-sha2-*|ssh-rsa) ;; *) die "unsupported forwarding SSH public key" ;; esac
        [[ "$push_key_data" =~ ^[A-Za-z0-9+/=]+$ ]] || die "invalid forwarding SSH public key"

        cat <<EOF | write_generated "$receiver" "$force" 0755
#!/usr/bin/env bash
set -Eeuo pipefail
readonly destination="$tulip_dir/.ecsc/traffic/"
readonly expected="rsync --server -logDtpre.iLsfxCIvu --timeout=20 --remove-source-files . \$destination"
case "\${SSH_ORIGINAL_COMMAND:-}" in
    health)
        printf 'rose-receiver-ok\n'
        ;;
    "\$expected")
        exec /usr/bin/rsync --server -logDtpre.iLsfxCIvu --timeout=20 --remove-source-files . "\$destination"
        ;;
    *)
        printf 'only Rose PCAP delivery is allowed\n' >&2
        exit 126
        ;;
esac
EOF
        local receiver_ssh_dir=/root/.ssh receiver_keys=/root/.ssh/authorized_keys receiver_tmp
        mkdir -p -- "$receiver_ssh_dir"; chmod 0700 "$receiver_ssh_dir"
        receiver_tmp="$(mktemp)"
        if [[ -f "$receiver_keys" ]]; then
            grep -v '[[:space:]]rose-pcap-push$' "$receiver_keys" >"$receiver_tmp" || true
        fi
        printf 'restrict,command="%s" %s %s rose-pcap-push\n' \
            "$receiver" "$push_key_type" "$push_key_data" >>"$receiver_tmp"
        install -m 0600 "$receiver_tmp" "$receiver_keys"
        rm -f -- "$receiver_tmp"
        durable_push=1
    fi

    local vm_ip="$vulnbox_ip" services_json
    services_json="$(build_services_json "$vm_ip" "${service_specs[@]}")"
    if [[ ! -e "$tulip_dir/.ecsc/metadata/services.json" ]]; then
        printf '%s\n' "$services_json" | write_generated "$tulip_dir/.ecsc/metadata/services.json" 0 0644
    elif ((force)) && ((${#service_specs[@]})); then
        printf '%s\n' "$services_json" | write_generated "$tulip_dir/.ecsc/metadata/services.json" 1 0644
    fi

    local use_caddy=1 bind_ip="127.0.0.1" ui_url site_host site_label tls_directive caddy_target_port=443
    if [[ -n "$ui_vpn_ip" ]]; then
        use_caddy=0; bind_ip="$ui_vpn_ip"; ui_url="http://$(url_host "$ui_vpn_ip"):$ui_port"
    else
        [[ -n "$domain" || -n "$public_ip" ]] || die "pass --domain or --public-ip for public HTTPS exposure, or --ui-vpn-ip for direct binding"
        if [[ -n "$domain" ]]; then
            site_host="$domain"
            ui_url="https://$(url_host "$site_host")"
            if ((public_port != 443)); then ui_url+=":$public_port"; fi
            site_label="https://$domain"
            tls_directive=""
        else
            site_host="$public_ip"
            ui_url="http://$(url_host "$site_host")"
            if ((public_port != 80)); then ui_url+=":$public_port"; fi
            site_label=":80"
            tls_directive=""
            caddy_target_port=80
        fi
        need_command openssl
        local password_file="$tulip_dir/.ecsc/public-auth-password"
        local hash_file="$tulip_dir/.ecsc/public-auth-hash"
        if [[ -z "$auth_password" && -s "$password_file" ]]; then auth_password="$(<"$password_file")"; fi
        [[ -n "$auth_password" ]] || auth_password="$(openssl rand -hex 16)"
        printf '%s\n' "$auth_password" | write_generated "$password_file" "$force" 0600
        local auth_hash
        if [[ -s "$hash_file" && "$force" != 1 ]]; then
            auth_hash="$(<"$hash_file")"
        else
            auth_hash="$(docker run --rm "$CADDY_IMAGE" caddy hash-password --plaintext "$auth_password")"
        fi
        printf '%s\n' "$auth_hash" | write_generated "$hash_file" "$force" 0600
        cat <<EOF | write_generated "$tulip_dir/Caddyfile.ecsc" "$force" 0644
$site_label {
    $tls_directive
    header {
        Strict-Transport-Security "max-age=31536000"
        X-Content-Type-Options "nosniff"
        Referrer-Policy "no-referrer"
        -Server
    }
    basic_auth {
        $auth_user $auth_hash
    }
    encode zstd gzip
    reverse_proxy frontend:3000
}
EOF
    fi

    cat <<EOF | write_generated "$tulip_dir/.env.ecsc" "$force" 0600
TIMESCALE=postgresql://tulip@timescale:5432/tulip
TRAFFIC_DIR_HOST=$tulip_dir/.ecsc/traffic
TRAFFIC_DIR_DOCKER=/traffic
TULIP_BIND_IP=$bind_ip
TULIP_UI_PORT=$ui_port
FLAG_REGEX='ECSC\{[A-Za-z0-9_-]{32}\}'
TICK_START=$tick_start
TICK_LENGTH=$FAUST_TICK_LENGTH_MS
FLAG_LIFETIME=$FAUST_FLAG_LIFETIME_TICKS
VM_IP=$vm_ip
SERVICES_JSON=$services_json
TEAM_ID=$team_id
FLAGID_SCRAPE=0
FLAGID_ENDPOINT=
VISUALIZER_URL=
FLAGID_SCAN=0
FLAG_VALIDATOR_TYPE=
FLAG_VALIDATOR_TEAM=
PCAP_OVER_IP=$([[ "$durable_push" == 1 ]] && printf '' || printf 'pcap-broker:4242')
DUMP_PCAPS=
DUMP_PCAPS_INTERVAL=0
DUMP_PCAPS_FILENAME=
BPF=tcp and not port 22 and not port 4444
EOF

    cat <<EOF | write_generated "$tulip_dir/.ecsc/service-sync.sh" "$force" 0755
#!/bin/sh
set -eu
while true; do
    temporary="\$(mktemp)"
    if ssh -i /root/.ssh/id_ed25519 -o BatchMode=yes -o StrictHostKeyChecking=yes \
        -o ConnectTimeout=10 root@$vulnbox_ip services >"\$temporary"; then
        cp "\$temporary" /config/.services.json
        mv /config/.services.json /config/services.json
    fi
    rm -f -- "\$temporary"
    sleep 60
done
EOF

    {
        cat <<EOF
services:
EOF
        if ((durable_push == 0)); then
            cat <<EOF
  pcap-broker:
    build:
      context: https://github.com/fox-it/pcap-broker.git#$PCAP_BROKER_REV
    image: ecsc-pcap-broker:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./.ecsc/ssh/id_ed25519:/root/.ssh/id_ed25519:ro
      - ./.ecsc/ssh/known_hosts:/root/.ssh/known_hosts:ro
    environment:
      LISTEN_ADDRESS: 0.0.0.0:4242
      PCAP_COMMAND: ssh -i /root/.ssh/id_ed25519 -o BatchMode=yes -o StrictHostKeyChecking=yes -o ConnectTimeout=10 -o ServerAliveInterval=30 -o ServerAliveCountMax=3 -o TCPKeepAlive=yes root@$vulnbox_ip capture

EOF
        fi
        cat <<EOF
  service-sync:
    build:
      context: https://github.com/fox-it/pcap-broker.git#$PCAP_BROKER_REV
    image: ecsc-pcap-broker:latest
    restart: unless-stopped
    entrypoint: /bin/sh
    command: /sync/service-sync.sh
EOF
        if ((durable_push == 0)); then
            cat <<EOF
    depends_on:
      - pcap-broker
EOF
        fi
        cat <<EOF
    network_mode: host
    volumes:
      - ./.ecsc/ssh/id_ed25519:/root/.ssh/id_ed25519:ro
      - ./.ecsc/ssh/known_hosts:/root/.ssh/known_hosts:ro
      - ./.ecsc/service-sync.sh:/sync/service-sync.sh:ro
      - ./.ecsc/metadata:/config

  api:
    volumes:
      - ./.ecsc/metadata:/config:ro
    environment:
      SERVICES_FILE: /config/services.json

  assembler:
    depends_on:
      - timescale
EOF
        if ((durable_push == 0)); then
            cat <<EOF
      - pcap-broker
EOF
        fi
        cat <<EOF
    environment:
      PCAP_OVER_IP: $([[ "$durable_push" == 1 ]] && printf '""' || printf 'host.docker.internal:4242')
    extra_hosts:
      - "host.docker.internal:host-gateway"
EOF
        if ((use_caddy)); then
            cat <<EOF

  caddy:
    image: $CADDY_IMAGE
    restart: unless-stopped
    ports:
      - "$public_port:$caddy_target_port"
    networks:
      - internal
    depends_on:
      - frontend
    volumes:
      - ./Caddyfile.ecsc:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config

volumes:
  caddy-data:
  caddy-config:
EOF
        fi
    } | write_generated "$tulip_dir/docker-compose.ecsc.yml" "$force" 0644

    log "offsite configuration ready"
    log "install this restricted key on the vulnbox: $public_key"
    if ((durable_push)); then
        log "ingest mode: durable vulnbox push with local retry queue"
    else
        log "ingest mode: legacy live stream; configure --push-public-key-file for disconnect-safe forwarding"
    fi
    log "UI: $ui_url"
    if ((use_caddy)); then log "UI user: $auth_user; password: $auth_password"; fi

    if ((start)); then
        local scan_tmp
        scan_tmp="$(mktemp)"
        if ! ssh-keyscan -T 5 "$vulnbox_ip" >"$scan_tmp" 2>/dev/null || [[ ! -s "$scan_tmp" ]]; then
            rm -f -- "$scan_tmp"
            die "cannot read the SSH host key from $vulnbox_ip; check the game VPN and vulnbox setup"
        fi
        if [[ -s "$known_hosts" ]]; then
            rm -f -- "$scan_tmp"
        else
            chmod 0644 "$scan_tmp"
            mv -f -- "$scan_tmp" "$known_hosts"
        fi

        ssh -i "$private_key" -o BatchMode=yes -o StrictHostKeyChecking=yes -o ConnectTimeout=10 \
            root@"$vulnbox_ip" services | python3 -m json.tool >/dev/null \
            || die "restricted SSH service check failed; run vulnbox mode first"
        (
            cd -- "$tulip_dir"
            docker compose --env-file .env.ecsc -f docker-compose.yml -f docker-compose.ecsc.yml config >/dev/null
            docker compose --env-file .env.ecsc -f docker-compose.yml -f docker-compose.ecsc.yml up -d --build
            if ((durable_push)); then
                docker rm -f "$(basename "$tulip_dir")-pcap-broker-1" >/dev/null 2>&1 || true
            fi
        )
        log "Rose and traffic ingestion started"
    fi
}

vulnbox_main() {
    local public_key_file="" public_key_literal="" team_id="" vulnbox_ip=""
    local game_interface="" capture_filter="tcp and not port 22 and not port 4242 and not port 4444"
    local offsite_host="" offsite_port=22 offsite_user=root offsite_dir="/root/tulip/.ecsc/traffic"
    local start=0 force=0
    while (($#)); do
        case "$1" in
            --public-key-file) public_key_file="${2:?missing value}"; shift 2 ;;
            --public-key) public_key_literal="${2:?missing value}"; shift 2 ;;
            --team-id) team_id="${2:?missing value}"; shift 2 ;;
            --vulnbox-ip) vulnbox_ip="${2:?missing value}"; shift 2 ;;
            --game-interface) game_interface="${2:?missing value}"; shift 2 ;;
            --capture-filter) capture_filter="${2:?missing value}"; shift 2 ;;
            --offsite-host) offsite_host="${2:?missing value}"; shift 2 ;;
            --offsite-port) offsite_port="${2:?missing value}"; shift 2 ;;
            --offsite-user) offsite_user="${2:?missing value}"; shift 2 ;;
            --offsite-dir) offsite_dir="${2:?missing value}"; shift 2 ;;
            --start) start=1; shift ;;
            --force) force=1; shift ;;
            -h|--help) usage; exit 0 ;;
            *) die "unknown vulnbox option: $1" ;;
        esac
    done

    [[ ${EUID:-$(id -u)} -eq 0 ]] || die "vulnbox mode must run as root"
    [[ -n "$public_key_literal" || -s "$public_key_file" ]] || die "pass --public-key-file or --public-key"
    if [[ -n "$team_id" ]]; then
        [[ "$team_id" =~ ^[0-9]+$ ]] || die "--team-id must be a number"
        ((team_id >= 1 && team_id <= 9999)) || die "--team-id must be between 1 and 9999"
    fi
    if [[ -n "$vulnbox_ip" ]]; then
        validate_ip "$vulnbox_ip" || die "invalid --vulnbox-ip: $vulnbox_ip"
    elif [[ -n "$team_id" ]]; then
        vulnbox_ip="fd66:666:${team_id}::2"
    fi
    validate_port "$offsite_port" || die "invalid --offsite-port"
    [[ "$offsite_user" =~ ^[A-Za-z_][A-Za-z0-9_-]*$ ]] || die "invalid --offsite-user"
    [[ "$offsite_user" == root ]] || die "the automated receiver currently requires --offsite-user root"
    [[ "$offsite_dir" =~ ^/[A-Za-z0-9_./-]+$ ]] || die "invalid --offsite-dir"
    if [[ -n "$offsite_host" ]]; then
        [[ "$offsite_host" =~ ^[A-Za-z0-9_.:-]+$ ]] || die "invalid --offsite-host"
    fi
    install_vulnbox_dependencies

    if [[ -z "$game_interface" ]]; then
        game_interface="$(ip -6 route get fd66:777::1 2>/dev/null | awk '{for (i=1; i<=NF; i++) if ($i == "dev") {print $(i+1); exit}}')"
        if [[ -z "$game_interface" ]]; then
            game_interface="$(ip -6 route show default 2>/dev/null | awk '{for (i=1; i<=NF; i++) if ($i == "dev") {print $(i+1); exit}}')"
        fi
    fi
    [[ -n "$game_interface" ]] || die "could not detect the game interface; pass --game-interface"
    ip link show dev "$game_interface" >/dev/null 2>&1 || die "interface does not exist: $game_interface"

    local key_type key_data
    if [[ -n "$public_key_literal" ]]; then
        read -r key_type key_data _ <<<"$public_key_literal"
    else
        read -r key_type key_data _ <"$public_key_file"
    fi
    case "$key_type" in ssh-ed25519|ecdsa-sha2-*|ssh-rsa) ;; *) die "unsupported SSH public key" ;; esac
    [[ "$key_data" =~ ^[A-Za-z0-9+/=]+$ ]] || die "invalid SSH public key"

    local vulnbox_config_ip="$vulnbox_ip"
    if [[ -z "$vulnbox_config_ip" ]]; then
        vulnbox_config_ip="$(
            ip -6 -o addr show dev "$game_interface" \
                | awk '{split($4, a, "/"); if (a[1] ~ /^fd66:666:/) {print a[1]; exit}}'
        )"
    fi
    if [[ -z "$vulnbox_config_ip" ]]; then
        vulnbox_config_ip="$(
            ip -6 -o addr show scope global dev "$game_interface" \
                | awk '{split($4, a, "/"); print a[1]; exit}'
        )"
    fi
    [[ -n "$vulnbox_config_ip" ]] || die "could not find the vulnbox IPv6 address on $game_interface"

    mkdir -p /etc/ecsc-tulip
    {
        printf 'VULNBOX_IP=%q\n' "$vulnbox_config_ip"
        printf 'GAME_INTERFACE=%q\n' "$game_interface"
        printf 'CAPTURE_FILTER=%q\n' "$capture_filter"
    } | write_generated /etc/ecsc-tulip/config "$force" 0600

    cat <<'PYTHON' | write_generated /usr/local/sbin/ecsc-tulip-discover-services "$force" 0755
#!/usr/bin/env python3
import json
import re
import subprocess
from pathlib import Path

CONFIG = Path("/etc/ecsc-tulip/config")
OVERRIDE = Path("/etc/ecsc-tulip/services.json")

def run(command):
    try:
        return subprocess.run(command, check=False, text=True, capture_output=True).stdout
    except FileNotFoundError:
        return ""

def config_ip():
    for line in CONFIG.read_text(encoding="utf-8").splitlines():
        if line.startswith("VULNBOX_IP="):
            return line.split("=", 1)[1].strip("'\"")
    raise RuntimeError("VULNBOX_IP missing")

def main():
    if OVERRIDE.is_file():
        print(json.dumps(json.loads(OVERRIDE.read_text(encoding="utf-8")), separators=(",", ":")))
        return
    names = {}
    for line in run(["docker", "ps", "--format", "{{.Names}}\\t{{.Ports}}"] ).splitlines():
        name, _, ports = line.partition("\t")
        for port in re.findall(r"(?<!\d)([1-9][0-9]{0,4})(?=->)", ports):
            if int(port) > 65535:
                continue
            names[int(port)] = re.sub(r"[^A-Za-z0-9_.-]+", "-", name).strip("-") or f"service-{port}"
    for port in re.findall(r":([1-9][0-9]{0,4})\b", run(["ss", "-H", "-ltn"])):
        port_number = int(port)
        if port_number <= 65535 and port_number != 22:
            names.setdefault(port_number, f"service-{port}")
    ip = config_ip()
    data = [{"ip": ip, "port": p, "name": names[p]} for p in sorted(names) if 1 <= p <= 65535 and p != 22]
    print(json.dumps(data or [{"ip": ip, "port": -1, "name": "other"}], separators=(",", ":")))

if __name__ == "__main__":
    main()
PYTHON

    cat <<'EOF' | write_generated /usr/local/sbin/ecsc-tulip-remote "$force" 0755
#!/usr/bin/env bash
set -Eeuo pipefail
# shellcheck source=/dev/null
source /etc/ecsc-tulip/config
case "${SSH_ORIGINAL_COMMAND:-}" in
    capture)
        exec tcpdump -U --immediate-mode -nn -i "$GAME_INTERFACE" -s 65535 -w - "$CAPTURE_FILTER"
        ;;
    services)
        exec /usr/local/sbin/ecsc-tulip-discover-services
        ;;
    *)
        printf 'only capture and services commands are allowed\n' >&2
        exit 126
        ;;
esac
EOF

    local ssh_dir=/root/.ssh authorized_keys=/root/.ssh/authorized_keys auth_tmp
    mkdir -p "$ssh_dir"; chmod 0700 "$ssh_dir"
    auth_tmp="$(mktemp)"
    if [[ -f "$authorized_keys" ]]; then
        grep -v '[[:space:]]ecsc-tulip-capture$' "$authorized_keys" >"$auth_tmp" || true
    fi
    printf 'restrict,command="/usr/local/sbin/ecsc-tulip-remote" %s %s ecsc-tulip-capture\n' \
        "$key_type" "$key_data" >>"$auth_tmp"
    install -m 0600 "$auth_tmp" "$authorized_keys"
    rm -f -- "$auth_tmp"

    if command -v systemctl >/dev/null 2>&1 && systemctl show-environment >/dev/null 2>&1; then
        systemctl enable --now ssh 2>/dev/null || systemctl enable --now sshd
    fi

    local push_key=/root/.ssh/rose-pcap-push push_public_key
    push_public_key="$push_key.pub"
    if [[ ! -s "$push_key" || ! -s "$push_public_key" ]]; then
        [[ ! -e "$push_key" && ! -e "$push_public_key" ]] \
            || die "incomplete forwarding key pair: $push_key"
        ssh-keygen -q -t ed25519 -N '' -C rose-pcap-push -f "$push_key"
    fi
    chmod 0600 "$push_key"; chmod 0644 "$push_public_key"

    if [[ -n "$offsite_host" ]]; then
        command -v systemctl >/dev/null 2>&1 \
            || die "durable forwarding currently requires systemd on the vulnbox"
        mkdir -p -- "$PCAP_SPOOL_DIR/active" "$PCAP_SPOOL_DIR/ready" "$FORWARDER_STATE_DIR" /run/lock
        chmod 0750 "$PCAP_SPOOL_DIR" "$PCAP_SPOOL_DIR/active" "$PCAP_SPOOL_DIR/ready"
        chmod 0700 "$FORWARDER_STATE_DIR"

        {
            printf 'VULNBOX_IP=%q\n' "$vulnbox_config_ip"
            printf 'GAME_INTERFACE=%q\n' "$game_interface"
            printf 'CAPTURE_FILTER=%q\n' "$capture_filter"
            printf 'OFFSITE_HOST=%q\n' "$offsite_host"
            printf 'OFFSITE_PORT=%q\n' "$offsite_port"
            printf 'OFFSITE_USER=%q\n' "$offsite_user"
            printf 'OFFSITE_DIR=%q\n' "$offsite_dir"
            printf 'PCAP_SPOOL_DIR=%q\n' "$PCAP_SPOOL_DIR"
            printf 'FORWARDER_STATE_DIR=%q\n' "$FORWARDER_STATE_DIR"
        } | write_generated /etc/ecsc-tulip/forwarder "$force" 0600

        cat <<'EOF' | write_generated /usr/local/sbin/rose-pcap-capture "$force" 0755
#!/usr/bin/env bash
set -Eeuo pipefail
set -f
# shellcheck source=/dev/null
source /etc/ecsc-tulip/forwarder
mkdir -p -- "$PCAP_SPOOL_DIR/active" "$PCAP_SPOOL_DIR/ready"
# CAPTURE_FILTER intentionally expands into tcpdump's filter argument vector.
# shellcheck disable=SC2086
exec /usr/bin/tcpdump -i "$GAME_INTERFACE" -nn -s 65535 -U -G 15 \
    -w "$PCAP_SPOOL_DIR/active/rose-%Y%m%d-%H%M%S.pcap" $CAPTURE_FILTER
EOF

        cat <<'EOF' | write_generated /usr/local/sbin/rose-pcap-stage "$force" 0755
#!/usr/bin/env bash
set -Eeuo pipefail
# shellcheck source=/dev/null
source /etc/ecsc-tulip/forwarder
active="$PCAP_SPOOL_DIR/active"
ready="$PCAP_SPOOL_DIR/ready"
mkdir -p -- "$active" "$ready"
newest="$(find "$active" -maxdepth 1 -type f -name '*.pcap' -printf '%T@ %p\n' \
    | sort -nr | head -n 1 | cut -d' ' -f2-)"
[[ -n "$newest" ]] || exit 0
while IFS= read -r -d '' capture; do
    [[ "$capture" == "$newest" ]] || mv -- "$capture" "$ready/"
done < <(find "$active" -maxdepth 1 -type f -name '*.pcap' -print0)
EOF

        cat <<'EOF' | write_generated /usr/local/sbin/rose-pcap-push "$force" 0755
#!/usr/bin/env bash
set -Eeuo pipefail
# shellcheck source=/dev/null
source /etc/ecsc-tulip/forwarder
exec 9>/run/lock/rose-pcap-push.lock
flock -n 9 || exit 0
mkdir -p -- "$PCAP_SPOOL_DIR/ready" "$FORWARDER_STATE_DIR"
if [[ "$OFFSITE_HOST" == *:* ]]; then
    remote="$OFFSITE_USER@[$OFFSITE_HOST]"
else
    remote="$OFFSITE_USER@$OFFSITE_HOST"
fi
if ! find "$PCAP_SPOOL_DIR/ready" -maxdepth 1 -type f -name '*.pcap' -print -quit | grep -q .; then
    exit 0
fi
/usr/bin/rsync -a --remove-source-files --timeout=20 \
    -e "/usr/bin/ssh -p $OFFSITE_PORT -i /root/.ssh/rose-pcap-push -o BatchMode=yes -o StrictHostKeyChecking=yes -o ConnectTimeout=5 -o ServerAliveInterval=10 -o ServerAliveCountMax=3 -o UserKnownHostsFile=/root/.ssh/rose-offsite-known-hosts" \
    "$PCAP_SPOOL_DIR/ready/" "$remote:$OFFSITE_DIR/"
date +%s >"$FORWARDER_STATE_DIR/last-success-epoch"
find "$PCAP_SPOOL_DIR/ready" -mindepth 1 -type d -empty -delete
EOF

        cat <<'EOF' | write_generated /usr/local/sbin/rose-pcap-health "$force" 0755
#!/usr/bin/env bash
set -Eeuo pipefail
# shellcheck source=/dev/null
source /etc/ecsc-tulip/forwarder
for unit in rose-pcap-capture.service rose-pcap-stage.timer rose-pcap-push.timer; do
    if ! systemctl is-active --quiet "$unit"; then
        logger -t rose-forwarder "restarting inactive unit: $unit"
        systemctl restart "$unit"
    fi
done
queued="$(find "$PCAP_SPOOL_DIR/ready" -maxdepth 1 -type f -name '*.pcap' | wc -l)"
queue_bytes="$(find "$PCAP_SPOOL_DIR/ready" -maxdepth 1 -type f -name '*.pcap' -printf '%s\n' \
    | awk '{total += $1} END {print total + 0}')"
now="$(date +%s)"
last=0
[[ -s "$FORWARDER_STATE_DIR/last-success-epoch" ]] && read -r last <"$FORWARDER_STATE_DIR/last-success-epoch"
if ((queued > 0 && now - last > 120)); then
    logger -p daemon.warning -t rose-forwarder \
        "forwarding delayed: queued_files=$queued queued_bytes=$queue_bytes last_success_epoch=$last"
    exit 1
fi
available_kb="$(df -Pk "$PCAP_SPOOL_DIR" | awk 'NR==2 {print $4}')"
if ((available_kb < 1048576)); then
    logger -p daemon.warning -t rose-forwarder "less than 1 GiB free in PCAP spool: available_kb=$available_kb"
    exit 1
fi
EOF

        cat <<'EOF' | write_generated /etc/systemd/system/rose-pcap-capture.service "$force" 0644
[Unit]
Description=Rose rotating packet capture
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=0

[Service]
Type=simple
ExecStart=/usr/local/sbin/rose-pcap-capture
Restart=always
RestartSec=1
KillSignal=SIGINT
TimeoutStopSec=20

[Install]
WantedBy=multi-user.target
EOF

        cat <<'EOF' | write_generated /etc/systemd/system/rose-pcap-stage.service "$force" 0644
[Unit]
Description=Stage completed Rose PCAP rotations

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/rose-pcap-stage
EOF

        cat <<'EOF' | write_generated /etc/systemd/system/rose-pcap-stage.timer "$force" 0644
[Unit]
Description=Continuously stage completed Rose PCAP rotations

[Timer]
OnBootSec=3s
OnUnitActiveSec=3s
AccuracySec=1s
Persistent=true
Unit=rose-pcap-stage.service

[Install]
WantedBy=timers.target
EOF

        cat <<'EOF' | write_generated /etc/systemd/system/rose-pcap-push.service "$force" 0644
[Unit]
Description=Push completed PCAPs to offsite Rose
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/rose-pcap-push
EOF

        cat <<'EOF' | write_generated /etc/systemd/system/rose-pcap-push.timer "$force" 0644
[Unit]
Description=Continuously push completed PCAPs to offsite Rose

[Timer]
OnBootSec=4s
OnUnitActiveSec=5s
AccuracySec=1s
Persistent=true
Unit=rose-pcap-push.service

[Install]
WantedBy=timers.target
EOF

        cat <<'EOF' | write_generated /etc/systemd/system/rose-pcap-health.service "$force" 0644
[Unit]
Description=Repair and monitor the Rose PCAP forwarder

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/rose-pcap-health
EOF

        cat <<'EOF' | write_generated /etc/systemd/system/rose-pcap-health.timer "$force" 0644
[Unit]
Description=Watchdog for continuous Rose PCAP forwarding

[Timer]
OnBootSec=30s
OnUnitActiveSec=30s
AccuracySec=2s
Persistent=true
Unit=rose-pcap-health.service

[Install]
WantedBy=timers.target
EOF

        if ((start)); then
            local known_hosts_tmp
            known_hosts_tmp="$(mktemp)"
            if ! ssh-keyscan -p "$offsite_port" -T 5 "$offsite_host" >"$known_hosts_tmp" 2>/dev/null \
                || [[ ! -s "$known_hosts_tmp" ]]; then
                rm -f -- "$known_hosts_tmp"
                die "cannot read the offsite SSH host key from $offsite_host:$offsite_port"
            fi
            if [[ -s /root/.ssh/rose-offsite-known-hosts ]]; then
                rm -f -- "$known_hosts_tmp"
            else
                install -m 0600 "$known_hosts_tmp" /root/.ssh/rose-offsite-known-hosts
                rm -f -- "$known_hosts_tmp"
            fi
            local receiver_status
            receiver_status="$(ssh -p "$offsite_port" -i "$push_key" -o BatchMode=yes \
                -o StrictHostKeyChecking=yes -o ConnectTimeout=5 \
                -o UserKnownHostsFile=/root/.ssh/rose-offsite-known-hosts \
                "$offsite_user@$offsite_host" health 2>/dev/null || true)"
            [[ "$receiver_status" == rose-receiver-ok ]] \
                || die "restricted offsite receiver check failed; install $push_public_key with offsite --push-public-key-file"
            systemctl daemon-reload
            systemctl enable --now \
                rose-pcap-capture.service rose-pcap-stage.timer rose-pcap-push.timer rose-pcap-health.timer
            systemctl start rose-pcap-stage.service
            systemctl start rose-pcap-push.service \
                || die "initial PCAP delivery failed; confirm the push public key is installed offsite"
            log "durable capture and forwarding started"
        else
            log "durable forwarding units installed; rerun with --start after installing $push_public_key offsite"
        fi
    fi

    log "restricted capture key installed"
    log "game interface: $game_interface"
    log "capture filter: $capture_filter"
    log "forwarding public key: $push_public_key"
    if [[ -z "$offsite_host" ]]; then
        log "copy that forwarding public key offsite, then rerun with --offsite-host and --start"
    fi
}

doctor_main() {
    local tulip_dir role=auto failures=0
    tulip_dir="$(default_tulip_dir)"
    while (($#)); do
        case "$1" in
            --tulip-dir) tulip_dir="${2:?missing value}"; shift 2 ;;
            --role) role="${2:?missing value}"; shift 2 ;;
            -h|--help) usage; exit 0 ;;
            *) die "unknown doctor option: $1" ;;
        esac
    done
    [[ "$role" == auto || "$role" == offsite || "$role" == vulnbox ]] \
        || die "--role must be auto, offsite, or vulnbox"
    if [[ "$role" == auto ]]; then
        if [[ -f /etc/ecsc-tulip/forwarder ]]; then role=vulnbox; else role=offsite; fi
    fi

    check_ok() { log "doctor: $1"; }
    check_fail() { printf 'error: doctor: %s\n' "$1" >&2; failures=$((failures + 1)); }

    if [[ "$(uname -s)" == Linux ]]; then
        check_ok "Linux host"
    else
        check_fail "deployment host must be Linux"
    fi
    if [[ "$role" == offsite ]]; then
        if [[ -d "$tulip_dir" && -f "$tulip_dir/docker-compose.yml" ]]; then
            check_ok "Rose checkout found at $tulip_dir"
        else
            check_fail "Rose checkout missing at $tulip_dir"
        fi
        if command -v docker >/dev/null 2>&1; then
            check_ok "Docker CLI: $(docker --version 2>/dev/null || printf unknown)"
            if docker compose version >/dev/null 2>&1; then
                check_ok "Docker Compose v2: $(docker compose version --short 2>/dev/null || printf installed)"
            else
                check_fail "Docker Compose v2 plugin is missing"
            fi
            if docker info >/dev/null 2>&1; then
                check_ok "Docker daemon reachable"
            else
                check_fail "Docker daemon is not reachable"
            fi
        else
            check_fail "Docker Engine is missing"
        fi
        for command in python3 rsync ssh ssh-keygen ssh-keyscan; do
            if command -v "$command" >/dev/null 2>&1; then
                check_ok "$command available"
            else
                check_fail "$command missing"
            fi
        done
        if [[ -f "$tulip_dir/services/timescale/Dockerfile" ]] \
            && grep -Eq 'clang19.*llvm19|llvm19.*clang19' "$tulip_dir/services/timescale/Dockerfile"; then
            check_ok "Timescale image uses clang19/llvm19"
        else
            check_fail "Timescale image is not pinned to clang19/llvm19"
        fi
        if [[ -f "$tulip_dir/.env.ecsc" && -f "$tulip_dir/docker-compose.ecsc.yml" ]] \
            && command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
            if (
                cd -- "$tulip_dir"
                docker compose --env-file .env.ecsc \
                    -f docker-compose.yml -f docker-compose.ecsc.yml config >/dev/null
            ); then
                check_ok "generated Compose configuration is valid"
            else
                check_fail "generated Compose configuration is invalid"
            fi
            if grep -q '^PCAP_OVER_IP=$' "$tulip_dir/.env.ecsc"; then
                if [[ -x /usr/local/sbin/rose-pcap-receive ]]; then
                    check_ok "durable offsite receiver installed"
                else
                    check_fail "durable mode configured but receiver is missing"
                fi
            else
                check_fail "legacy stream ingest is configured; durable push is not active"
            fi
            if docker info >/dev/null 2>&1; then
                local running_services service
                running_services="$(
                    cd -- "$tulip_dir"
                    docker compose --env-file .env.ecsc \
                        -f docker-compose.yml -f docker-compose.ecsc.yml \
                        ps --status running --services 2>/dev/null || true
                )"
                for service in timescale api frontend assembler service-sync; do
                    if grep -qx "$service" <<<"$running_services"; then
                        check_ok "$service container running"
                    else
                        check_fail "$service container is not running"
                    fi
                done
            fi
        else
            check_fail "run offsite setup to create .env.ecsc and docker-compose.ecsc.yml"
        fi
    else
        for command in tcpdump python3 rsync ssh ssh-keygen ssh-keyscan flock systemctl; do
            if command -v "$command" >/dev/null 2>&1; then
                check_ok "$command available"
            else
                check_fail "$command missing"
            fi
        done
        if [[ -s /etc/ecsc-tulip/forwarder ]]; then
            check_ok "forwarder configuration installed"
        else
            check_fail "forwarder configuration missing"
        fi
        if [[ -s /root/.ssh/rose-pcap-push && -s /root/.ssh/rose-offsite-known-hosts ]]; then
            check_ok "forwarding identity and pinned host key installed"
        else
            check_fail "forwarding key or offsite known-host key missing"
        fi
        for unit in rose-pcap-capture.service rose-pcap-stage.timer rose-pcap-push.timer rose-pcap-health.timer; do
            if systemctl is-enabled --quiet "$unit" && systemctl is-active --quiet "$unit"; then
                check_ok "$unit enabled and active"
            else
                check_fail "$unit is not both enabled and active"
            fi
        done
        if [[ -d "$PCAP_SPOOL_DIR/ready" ]]; then
            local queued last now available_kb
            queued="$(find "$PCAP_SPOOL_DIR/ready" -maxdepth 1 -type f -name '*.pcap' | wc -l | tr -d ' ')"
            check_ok "durable retry queue contains $queued file(s)"
            now="$(date +%s)"; last=0
            [[ -s "$FORWARDER_STATE_DIR/last-success-epoch" ]] \
                && read -r last <"$FORWARDER_STATE_DIR/last-success-epoch"
            if ((queued > 0 && now - last > 120)); then
                check_fail "retry queue has not delivered successfully in the last two minutes"
            elif ((last > 0)); then
                check_ok "forwarder has a recorded successful delivery"
            fi
            available_kb="$(df -Pk "$PCAP_SPOOL_DIR" | awk 'NR==2 {print $4}')"
            if ((available_kb >= 1048576)); then
                check_ok "PCAP spool has at least 1 GiB free"
            else
                check_fail "PCAP spool has less than 1 GiB free"
            fi
        else
            check_fail "durable retry queue is missing"
        fi
    fi

    ((failures == 0)) || die "doctor found $failures problem(s)"
    log "doctor: Rose deployment is compatible and healthy"
}

main() {
    (($#)) || { usage; exit 1; }
    local mode="$1"; shift
    case "$mode" in
        offsite) offsite_main "$@" ;;
        vulnbox) vulnbox_main "$@" ;;
        doctor) doctor_main "$@" ;;
        -h|--help|help) usage ;;
        *) usage >&2; die "first argument must be offsite, vulnbox, or doctor" ;;
    esac
}

main "$@"
